In [31]:
import torch
x = torch.tensor([2., 99,2,1,9], requires_grad=True)

In [32]:
x # computational grash

tensor([ 2., 99.,  2.,  1.,  9.], requires_grad=True)

In [33]:
y = (x+31).mean()
y

tensor(53.6000, grad_fn=<MeanBackward0>)

In [34]:
y.backward()

In [35]:
x.grad

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])

In [39]:
x = torch.tensor([2., 99,2,1,9], requires_grad=True)
y = (x+31).sum()
print(y)
y.backward()
x.grad

tensor(268., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1., 1.])

In [40]:
x = torch.tensor([2., 99,2,1,9], requires_grad=True)
y = (x+31).mean()
print(y)
y.backward()
x.grad

tensor(53.6000, grad_fn=<MeanBackward0>)


tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])

tensor(268., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1., 1.])

In [6]:
# how to understand back

In [24]:
a = torch.tensor([2., 99,2,1,9], requires_grad=True)

In [25]:
b  = torch.tensor([1., 1,1,1,1], requires_grad=True)

In [26]:
z=(a*b).mean()
#z=(a*b).sum()

In [27]:
z

tensor(22.6000, grad_fn=<MeanBackward0>)

In [28]:
z.backward()

In [29]:
a.grad

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])

In [30]:
b.grad

tensor([ 0.4000, 19.8000,  0.4000,  0.2000,  1.8000])